version: '3.7'

services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample
      MYSQL_PASSWORD: password
    ports:
      - 4306:3306
    volumes:
      - mysql-db:/var/lib/mysql
  redis:
    image: "redis:5.0.5"
    ports:
      - "6379:6379"
    command: redis-server
    volumes:
      - "./data/redis:/data"
  backend:
    environment:
      REDIS_URL: redis://redis:6379/0
    tty: true
    depends_on:
      - db
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    command: rails server -b 0.0.0.0
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/app:/usr/src/app
    command: 'yarn dev'
    ports:
      - "8000:3000"
  openapi-generator:
    image: openapitools/openapi-generator-cli
    volumes:
      - ./:/local
    command: generate -g typescript-axios -i /local/backend/openapi.yml -o /local/frontend/app/src/openapi-generator
  stoplight-prism:
    image: stoplight/prism
    ports:
      - "4010:4010"
    command: mock -h 0.0.0.0 /openapi.yml
    volumes:
      - ./backend/openapi.yml:/openapi.yml
volumes:
  mysql-db:
    driver: local
