inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 35

Metrics/AbcSize:
  Max: 40

Metrics/BlockLength:
  Max: 30

Metrics/ClassLength:
  Max: 200

Layout/LineLength:
  Max: 200

RSpec/AnyInstance:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false
