name: Frontend Test

on:
  push:
    paths:
      - "frontend/app/**"
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: frontend/app
          group: "E2E Tests"
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"
          record: true
    env:
      FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
      NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY }}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
      NEXT_PUBLIC_FIREBASE_DATABASE_URL: ${{ secrets.NEXT_PUBLIC_FIREBASE_DATABASE_URL }}
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
      FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
      COOKIE_SECRET_CURRENT: ${{ secrets.COOKIE_SECRET_CURRENT }}
      COOKIE_SECRET_PREVIOUS: ${{ secrets.COOKIE_SECRET_PREVIOUS }}
      NEXT_PUBLIC_COOKIE_SECURE: ${{ secrets.NEXT_PUBLIC_COOKIE_SECURE }}
      CYPRESS_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY }}
      CYPRESS_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
      CYPRESS_FIREBASE_DATABASE_URL: ${{ secrets.NEXT_PUBLIC_FIREBASE_DATABASE_URL }}
      CYPRESS_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
      CYPRESS_FIREBASE_STORAGE_BUCKET: ${{ secrets.CYPRESS_FIREBASE_STORAGE_BUCKET }}
      CYPRESS_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.CYPRESS_FIREBASE_MESSAGING_SENDER_ID }}
      CYPRESS_FIREBASE_APP_ID: ${{ secrets.CYPRESS_FIREBASE_APP_ID }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
      CYPRESS_TEST_UID: ${{ secrets.TEST_UID }}
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
      GITHUB_HEAD_REF: ${{ github.head_ref }}
      GITHUB_REF: ${{ github.ref }}
